import math

from subsystems.interop import ObjectType

STATE_CHANGE_DELAY = 1.5 # Seconds

MIN_ROTATE_TIME  = 8
MAX_TRAVEL_TIME  = 5

DIST_THRESH      = 10
HEAD_THRESH      = 5
HEAD_SENSITIVITY = 3
PRUNE_TIME       = 0.75

CONTROL_KP = 1
CONTROL_KI = 0.000
CONTROL_KD = 0
CONTROL_HEAD_MAX = 0.5 # 1 radian is max corrrection

ROTATE_DEAD_ZONE = math.radians(2)

ROTATE_SPEED_FAST = 0.4
ROTATE_SPEED_MED  = 0.37
ROTATE_SPEED_SLOW = 0.33

MOVE_SPEED_FAST  = 0.32
MOVE_SPEED_MED   = 0.3
MOVE_SPEED_SLOW  = 0.25

NAV_DIST_ROCK   = 35
NAV_DIST_SAMPLE = 35
NAV_DIST_LANDER = 30

LOOKAT_THRESH_SAMPLE = 4
LOOKAT_THRESH_ROCK   = 4
LOOKAT_THRESH_LANDER = 4

APPROACH_TIME_ROCK   = 1.5
APPROACH_TIME_SAMPLE = 2
APPROACH_TIME_LANDER = 6

DISC_TIMEOUT_SAMPLE  = 10 

AVOID_MOVE_TIME = 2

AVOID_RADIUS = {}
AVOID_RADIUS[ObjectType.OBSTACLE] = 17
AVOID_RADIUS[ObjectType.SAMPLE]   = 6
AVOID_RADIUS[ObjectType.ROCK]     = 10
AVOID_RADIUS[ObjectType.LANDER]   = 20
