import math

from subsystems.interop import ObjectType

STATE_CHANGE_DELAY = 1.5 # Seconds

MIN_ROTATE_TIME  = 8
MAX_TRAVEL_TIME  = 5

DIST_THRESH      = 10
HEAD_THRESH      = 5
PRUNE_TIME       = 0.5

ROTATE_DEAD_ZONE = 6
ROTATE_STOP      = 2.5

ROTATE_SPEED_FAST = 0.3
ROTATE_SPEED_MED  = 0.3
ROTATE_SPEED_SLOW = 0.3

MOVE_SPEED_FAST  = 0.4
MOVE_SPEED_MED   = 0.31
MOVE_SPEED_SLOW  = 0.23

NAV_DIST_ROCK   = 35
NAV_DIST_SAMPLE = 35
NAV_DIST_LANDER = 30

LOOKAT_THRESH_SAMPLE = 3.5
LOOKAT_THRESH_ROCK   = 3.5
LOOKAT_THRESH_LANDER = 3.5

APPROACH_TIME_ROCK   = 1.1
APPROACH_TIME_SAMPLE = 2.2
APPROACH_TIME_LANDER = 2.75

DISC_TIMEOUT_SAMPLE  = 10

AVOID_MOVE_TIME = 2

AVOID_RADIUS = {}
AVOID_RADIUS[ObjectType.OBSTACLE] = 17
AVOID_RADIUS[ObjectType.SAMPLE]   = 6
AVOID_RADIUS[ObjectType.ROCK]     = 10
AVOID_RADIUS[ObjectType.LANDER]   = 20
