import math

from subsystems.interop import ObjectType

STATE_CHANGE_DELAY = 1.5 # Seconds

MIN_ROTATE_TIME  = 8
MAX_TRAVEL_TIME  = 2

DIST_THRESH = 10
HEAD_THRESH = 5
PRUNE_TIME  = 0.5

ROTATE_DEAD_ZONE = 8
ROTATE_STOP      = 2.5

ROTATE_EXPLORE = 0.3
ROTATE_NAV     = 0.2
ROTATE_LOOKAT  = 0.05

MOVE_EXPLORE = 0.015
MOVE_NAV     = 0.015
MOVE_FLIP    = 0.03
MOVE_DROP    = 0.05
MOVE_COLLECT = 0.03

NAV_DIST_ROCK   = 20
NAV_DIST_SAMPLE = 15
NAV_DIST_LANDER = 30

LOOKAT_THRESH_SAMPLE = 1.5
LOOKAT_THRESH_ROCK   = 1.5
LOOKAT_THRESH_LANDER = 1.5

APPROACH_TIME_ROCK   = 2
APPROACH_TIME_SAMPLE = 3
APPROACH_TIME_LANDER = 2

DISC_TIMEOUT_SAMPLE  = 10 
LOOKAT_TIMEOUT       = 5

AVOID_MOVE_TIME = 2

AVOID_RADIUS = {}
AVOID_RADIUS[ObjectType.OBSTACLE] = 17
AVOID_RADIUS[ObjectType.SAMPLE]   = 6
AVOID_RADIUS[ObjectType.ROCK]     = 10
AVOID_RADIUS[ObjectType.LANDER]   = 20
