import math

from subsystems.interop import ObjectType

STATE_CHANGE_DELAY = 1.5 # Seconds

MIN_ROTATE_TIME  = 8
MAX_TRAVEL_TIME  = 2

DIST_THRESH      = 10
HEAD_THRESH      = 5
PRUNE_TIME       = 0.5

ROTATE_DEAD_ZONE = 8
ROTATE_STOP      = 4

ROTATE_EXPLORE = 0.35
ROTATE_NAV     = 0.3
ROTATE_LOOKAT  = 0.25

MOVE_EXPLORE    = 0.3
MOVE_NAV        = 0.27
MOVE_FLIP       = 0.3
MOVE_DROP       = 0.5
MOVE_COLLECT    = 0.3

NAV_DIST_ROCK   = 35
NAV_DIST_SAMPLE = 35
NAV_DIST_LANDER = 30

LOOKAT_THRESH_SAMPLE = 2
LOOKAT_THRESH_ROCK   = 2
LOOKAT_THRESH_LANDER = 2

APPROACH_TIME_ROCK   = 2
APPROACH_TIME_SAMPLE = 2
APPROACH_TIME_LANDER = 2

DISC_TIMEOUT_SAMPLE  = 10

AVOID_MOVE_TIME = 2

AVOID_RADIUS = {}
AVOID_RADIUS[ObjectType.OBSTACLE] = 17
AVOID_RADIUS[ObjectType.SAMPLE]   = 6
AVOID_RADIUS[ObjectType.ROCK]     = 10
AVOID_RADIUS[ObjectType.LANDER]   = 20
